version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-xploresg-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - mynetwork
    # restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000"]
    #   interval: 60s
    #   timeout: 10s
    #   retries: 3
    # depends_on:
    #   - backend

  user-service:
    build:
      context: ./backend/services/auth
      dockerfile: Dockerfile.dev # Specify the development Dockerfile
    container_name: auth-service-xploresg-dev
    env_file:
      - ./backend/services/auth/.env
    volumes:
      - ./backend/services/auth:/app
      - user_node_modules:/app/node_modules
    networks:
      - mynetwork
    ports:
      - "4000:4000"
    # restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
    #   interval: 60s
    #   timeout: 10s
    #   retries: 3

volumes:
  frontend_node_modules:
  user_node_modules:

networks:
  mynetwork:
    driver: bridge
