name: Backend-CI

on:
  push:
    branches:
      - master
      - "feature/XPLSG-**" # This will trigger the workflow for all branches that start with XPLSG-
    # paths:
    #   - backend/** # This will trigger the workflow for all changes in the frontend directory
  pull_request:
    branches:
      - master
      - "feature/XPLSG-**" # This will trigger the workflow for all branches that start with XPLSG-
    # paths:
    #   - backend/** # This will trigger the workflow for all changes in the frontend directory

jobs:
  fastapi-tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Python 3.10
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          cd backend/fastapi
          pip install -r requirements.txt

      # Run tests
      - name: Run tests
        run: |
          cd backend/fastapi
          pytest

  express-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd backend/services/user
          npm install

      - name: Run tests
        run: |
          cd backend/services/user
          npm run test
